#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/bootstrap/env.php';

// Instantiate the app
$settings = require __DIR__ . '/config/settings.php';
$app = new \Slim\App($settings);

// Set up console
require __DIR__ . '/bootstrap/console.php';

$di = $app->getContainer();

$cli = new \Symfony\Component\Console\Application();

# add our commands
$cli->add($di->get($argv[1]));

$cli->run();
?>